added rxjs and provider for auth
projector-react/projector-vadym pull request #3
Opened 2022-07-06 18:18 UTC by vadymshukr

2022-07-07 18:13 UTC, maxzag requested changes
Також якщо ти вже обрав класовий підхід я запропонував би використання модифікаторів доступу - private, public

2022-07-07 18:13 UTC, maxzag commented on src/Auth/auth-state.ts
> +        this.logoutResult$ = this.logoutResult$.bind(this)
якщо ти будешь підписуватися тільки на гетер isAuthenticated$ в такому випадкку це не потрібно біндити

2022-07-07 18:13 UTC, maxzag commented on src/Auth/auth-state.ts
> +            switchMap(async (creds: LoginCredentials) => this.registerPostRequest(creds) as any)
намагайся уникати any

2022-07-10 14:47 UTC, Rastopyr requested changes

2022-07-10 14:47 UTC, Rastopyr commented on src/Auth/auth-context.tsx
> +const apiService = new AxiosApiService(createAxiosInstance())
Давай в наступному ПР зробмо все по DI, тобто треба буде створити composition-root та там об'явити весь граф залежностей

2022-07-10 14:47 UTC, Rastopyr commented on src/Auth/auth-state.ts
> +    private loginResult$() {
я думаю що методи тут зайви. можна одразу створити ці потоки там де є загальний стейт

2022-07-10 14:47 UTC, Rastopyr commented on src/Auth/auth-state.ts
> +    public isAuthenticated$() {
це може бути просто проперті класса

2022-07-12 19:21 UTC, Rastopyr requested changes

2022-07-12 19:21 UTC, Rastopyr commented on src/Auth/auth-state.ts
> +        const registerResult$ = () => this.onRegister$.pipe(
ці всі функціі можут бути константами.

```typescript
const loginResults$ = this.onLogin$.pipe(...)
```

2022-07-12 19:21 UTC, Rastopyr commented on src/Auth/auth-state.ts
> +        const registerResult$ = () => this.onRegister$.pipe(
немає ниякой потреби в функціях, тк потоки одразу lazy та запускаются коли є підпісчик

2022-07-13 12:09 UTC, Rastopyr approved these changes

2022-07-13 12:09 UTC, Rastopyr commented on src/Auth/auth-context.tsx
> +import { container } from '../compostion-root/composition-root'
Тут ще є посилання на composition-root. Тобто цей auth-context неявно залежить від всього іншого проєекту, пропоную в наступному ПР зробити все по DI

@maxzag та @iamr0man можуть підказати, вони вже наче таку проблему вирішували

2022-07-13 12:13 UTC, merged